# package version for all application JARs
version=1.0-SNAPSHOT

# plugin versions
springBootPluginVersion=3.5.14
springDependencyManagementPluginVersion=1.1.7
versionsPluginVersion=0.54.0

# dependency versions
springDocVersion=2.8.17
sgrSpecVersion=2.3_2026-05-28
sgrApiVersion=2.4.0
sgrJavaVersion=2.6.0
sgrModbusVersion=1.1.0
sgrRestVersion=2.2.0
sgrMessagingVersion=2.1.0

# config
org.gradle.daemon=false
