openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /value/{device}/{functionalProfile}/{dataPoint}:
    get:
      tags:
      - communications-controller
      operationId: getVal
      parameters:
      - name: device
        in: path
        required: true
        schema:
          type: string
      - name: functionalProfile
        in: path
        required: true
        schema:
          type: string
      - name: dataPoint
        in: path
        required: true
        schema:
          type: string
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
    post:
      tags:
      - communications-controller
      operationId: setVal
      parameters:
      - name: device
        in: path
        required: true
        schema:
          type: string
      - name: functionalProfile
        in: path
        required: true
        schema:
          type: string
      - name: dataPoint
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValueDto'
        required: true
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        "200":
          description: OK
  /eiXml/{fileName}:
    post:
      tags:
      - external-interface-xml-controller
      operationId: save
      parameters:
      - name: fileName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
              - file
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/EntityModelExternalInterfaceXml'
  /device:
    get:
      tags:
      - device-controller
      operationId: getAll_1
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeviceDto'
    post:
      tags:
      - device-controller
      operationId: insertOrUpdateDevice
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceDto'
        required: true
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DeviceDto'
  /eiXml:
    get:
      tags:
      - external-interface-xml-controller
      operationId: getAll
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExternalInterfaceXml'
  /eiXml/{name}:
    get:
      tags:
      - external-interface-xml-controller
      operationId: externalInterfaceXml
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExternalInterfaceXml'
    delete:
      tags:
      - external-interface-xml-controller
      operationId: delete
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        "200":
          description: OK
  /device/{deviceName}:
    get:
      tags:
      - device-controller
      operationId: getDevice
      parameters:
      - name: deviceName
        in: path
        required: true
        schema:
          type: string
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DeviceDto'
    delete:
      tags:
      - device-controller
      operationId: deleteDevice
      parameters:
      - name: deviceName
        in: path
        required: true
        schema:
          type: string
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        "200":
          description: OK
components:
  schemas:
    ValueDto:
      type: object
      properties:
        value:
          type: object
    EntityModelExternalInterfaceXml:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        xml:
          type: string
        _links:
          $ref: '#/components/schemas/Links'
    ExternalInterfaceXml:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        xml:
          type: string
    Links:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Link'
    ConfigurationValue:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        val:
          type: string
    DeviceDto:
      type: object
      properties:
        name:
          type: string
        eiXmlName:
          type: string
        configurationValues:
          type: array
          items:
            $ref: '#/components/schemas/ConfigurationValue'
        status:
          type: string
    Link:
      type: object
      properties:
        href:
          type: string
        hreflang:
          type: string
        title:
          type: string
        type:
          type: string
        deprecation:
          type: string
        profile:
          type: string
        name:
          type: string
        templated:
          type: boolean
